export enum OrderStatus {
  PENDING = 'PENDING',
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  PENDING_PRESCRIPTION = 'PENDING_PRESCRIPTION',
  CONFIRMED = 'CONFIRMED',
  PREPARING = 'PREPARING',
  SHIPPED = 'SHIPPED',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
}

export enum PaymentMethod {
  BANK_TRANSFER = 'BANK_TRANSFER',
  CASH_ON_DELIVERY = 'CASH_ON_DELIVERY',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  PROOF_UPLOADED = 'PROOF_UPLOADED',
  VERIFIED = 'VERIFIED',
  FAILED = 'FAILED',
  COMPLETED = 'COMPLETED',
}

export enum PrescriptionStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum InventoryMovementType {
  PURCHASE = 'PURCHASE',
  SALE = 'SALE',
  ADJUSTMENT = 'ADJUSTMENT',
  RETURN = 'RETURN',
  LOSS = 'LOSS',
  TRANSFER = 'TRANSFER',
  EXPIRED = 'EXPIRED',
}

export enum ProductType {
  MEDICINE = 'MEDICINE',
  SUPPLEMENT = 'SUPPLEMENT',
  PERSONAL_CARE = 'PERSONAL_CARE',
  BABY = 'BABY',
  DEVICE = 'DEVICE',
  OTHER = 'OTHER',
}

export enum PromotionType {
  PERCENTAGE = 'PERCENTAGE',
  FIXED_AMOUNT = 'FIXED_AMOUNT',
  BUY_X_GET_Y = 'BUY_X_GET_Y',
  FREE_SHIPPING = 'FREE_SHIPPING',
}

export enum BannerPosition {
  HOME_HERO = 'HOME_HERO',
  HOME_SECONDARY = 'HOME_SECONDARY',
  CATEGORY_TOP = 'CATEGORY_TOP',
  SIDEBAR = 'SIDEBAR',
  CHECKOUT = 'CHECKOUT',
}

export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  PHARMACIST = 'PHARMACIST',
  WAREHOUSE = 'WAREHOUSE',
  SALES = 'SALES',
  CUSTOMER = 'CUSTOMER',
}

export enum StockAlertType {
  LOW_STOCK = 'LOW_STOCK',
  EXPIRING_SOON = 'EXPIRING_SOON',
  EXPIRED = 'EXPIRED',
  OUT_OF_STOCK = 'OUT_OF_STOCK',
}

export enum PurchaseOrderStatus {
  DRAFT = 'DRAFT',
  SENT = 'SENT',
  PARTIALLY_RECEIVED = 'PARTIALLY_RECEIVED',
  RECEIVED = 'RECEIVED',
  CANCELLED = 'CANCELLED',
}
